language: generic
sudo: required
services: 
  - docker

before_install: 
  - docker build -t tobrien6115/react-test -f ./client/Dockerfile.dev ./client

script: 
  - docker run -e CI=true tobrien6115/react-test npm test

after_success:
  - docker build -t tobrien6115/multi-client ./client
  - docker build -t tobrien6115/multi-nginx ./nginx
  - docker build -t tobrien6115/multi-server ./server 
  - docker build -t tobrien6115/multi-worker ./worker 

  - echo "$docker_password" | docker login -u "$docker_id" --password-stdin

  #push to docker hub registry
  - docker push tobrien6115/multi-client
  - docker push tobrien6115/multi-nginx
  - docker push tobrien6115/multi-server
  - docker push tobrien6115/multi-worker
